export const users = [
    { id: 'btn1', district: "Kandy",
    destinations:{des1:{place:'Temple of Tooth Relic',pic:'src/assets/places_images/Temple_of_tooth_relic.jpg',content:'Sri Dalada Maligawa[a], commonly known in English as the Temple of the Sacred Tooth Relic, is a Buddhist temple in Kandy, Sri Lanka. It is located in the Royal Palace Complex of the former Kingdom of Kandy, which houses the relic of the tooth of the Buddha. Since ancient times, the relic has played an important role in local politics because it is believed that whoever holds the relic holds the governance of the country. The relic was historically held by Sinhalese kings. The Temple of the Tooth is a World Heritage Site mainly due to the temple and the relic.'},
        des2:{place :'Royal Botanic Gardens',pic:'src/assets/places_images/peradeniya_gardens.jpg',content:'Royal Botanic Gardens, Peradeniya are about 5.5 km to the west of the city of Kandy in the Central Province of Sri Lanka. In 2016, the garden was visited by 1.2 million locals and 400,000 foreign visitors.[1] It is near the Mahaweli River (the longest river in Sri Lanka).[2] It is renowned for its collection of orchids. The garden includes more than 4000 species of plants, including orchids, spices, medicinal plants and palm trees.[3] Attached to it is the "National Herbarium of Sri Lanka". The total area of the botanical garden is 147 acres (0.59 km2), at 460 meters above sea level, and with a 200-day annual rainfall. It is managed by the Department of national botanic gardens.'},
    des3:{place:'Udawattakele Forest Reserve', pic:'src/assets/places_images/udawatta-kele-sanctuary.jpg',content:'Udawattakele Forest Reserve often spelled as Udawatta Kele, is a historic forest reserve on a hill-ridge in the city of Kandy. It is 104 hectares (257 acres) large. During the days of the Kandyan kingdom, Udawattakele was known as "Uda Wasala Watta" in Sinhalese meaning "the garden above the royal palace". The sanctuary is famous for its extensive avifauna. The reserve also contains a great variety of plant species, especially lianas, shrubs and small trees. There are several giant lianas. Many of small and medium size mammals that inhabit Sri Lanka can be seen here. Several kinds of snakes and other reptiles might be seen. Udawattakele was designated as a forest reserve in 1856, and it became a sanctuary in 1938.'}}},
    { id: 'btn2', district: "Matale",
        destinations:{des1:{pic:'src/assets/places_images/matale_kovil.jpg',content:'Muthumariamman Temple (Tamil: முத்து மாரியம்மன் கோவில்) or Arulmigu Sri Muthumari Amman Kovil is a Hindu temple in Matale, Sri Lanka.\n' +
                    '\n' +
                    'The prefix "muthu" literally means pearl. "Mari" means rain and "Amman" means mother in Tamil language. The temple is dedicated to Mariamman, the goddess of rain and fertility. The chariot festival in this temple is held usually coinciding with Magam on a Full Moon Poya Day'},des2:{pic:'src/assets/places_images/logo.png',content:'ttttttt t t tttttttt'}}},
    // { id: 'btn2', district: "Matale", age: 30 }
];